name: Calculate Repository Size

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  calculate_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate repository size
        id: calculate_size
        run: |
          size=$(du -sh | awk '{print $1}')
          echo "Repository size is $size"
          echo $size > repository_size.txt
          
          # Display the size in the GitHub Actions logs
          echo "Repository size is $size"
          
      - name: Publish repository size as artifact
        uses: actions/upload-artifact@v2
        with:
          name: repository-size
          path: repository-size.txt
