name: Repository Size

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  repo_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate repository size
        id: size
        run: |
          size=$(du -sh | awk '{print $1}')
          echo "::set-output name=size::$size"

      - name: Display repository size
        run: echo "Repository Size-> ${{ steps.size.outputs.size }}"

  update_readme:
    needs: repo_size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Update README
        run: |
          echo "[![Repository Size](https://img.shields.io/badge/Repository%20Size-${{ needs.repo_size.outputs.size }}-blue)](https://github.com/swafit/licerepo)" > README.md
          git add README.md
          git commit -m "Update README with repository size badge" || echo "No changes to commit"
          git push
